server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:plip_video}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: video
    prefer-ip-address: false
    instance-id: ${spring.application.name}:docker:${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

plip:
  aws:
    enabled: ${AWS_ENABLED:true}
